### ISSUE TITLE
[Feature] Thumbnail Images for Posts

### ISSUE THREAD

**Issue by akhildevelops** [xypnox/blag#28]
It would be nice to have thumbnail images in posts.

Similar to this: https://enforcer007.github.io/

Size of thumbnails can be configured in config.toml under extras section.

``` toml
post__thumbnail = { height = "200px" }
```

Let me know if interested. I can give a PR for this

**Comment by akhildevelops** [comment]
Closing as it there's no response.

**Comment by xypnox** [comment]
Hi, I added thumbnails for a short time, but it was hard for me to manage different sizes, moreover I thought content was more compact without them in the homepage. 

I have also paused some development on the blog as I have plans to make something else rather than just a SSG.
