### ISSUE TITLE
Add options to configure the plugins

### ISSUE THREAD

**Issue by yashrsharma44** [xypnox/blag#4]
While using the theme, I found out that the link of the disqus, personal web page was hardcoded. It would be nice, if we could configure them through the toml file that we have, makes it easier to configure them

**Comment by xypnox** [comment]
Thanks for pointing this out, the feature to set the disqus shortcode has been added.
The documentation for the same is in the theme's README.

[Commit: c0242be0044c500ee0ca745b173eff39a4d67f61](https://github.com/xypnox/blag/commit/c0242be0044c500ee0ca745b173eff39a4d67f61)

@yashrsharma44 What do you refer to with the link to  personal web page?
