### ISSUE TITLE
Add a notes section in the blag

### ISSUE THREAD

**Issue by yashrsharma44** [xypnox/blag#5]
Like while I open the main page, I have a list of posts.
However, I want to add a notes section, and while I open it, I can have another list of posts which are my notes. 
Any suggestions how to do this?

**Comment by xypnox** [comment]
Have you tried the [sections](https://www.getzola.org/documentation/content/section/)? This will result in a simple structure with all notes in `notes` directory. In the section's index, you can add `transparent = false`  to not include it's contents in the homepage. Thus the files in the notes will be separate and from the one in the index.

**Comment by xypnox** [comment]
@yashrsharma44 Did it accomplish your goal?

**Comment by yashrsharma44** [comment]
Yup, this solved the issue 💯
